CREATE DATABASE IF NOT EXISTS Score;
USE Score;

CREATE TABLE IF NOT EXISTS score (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  tiempo TIME NOT NULL,
  puntos INT NOT NULL,
  fecha DATE NOT NULL,
  categoria VARCHAR(40) NOT NULL DEFAULT 'General',
  dificultad VARCHAR(20) NOT NULL DEFAULT 'Media',
  resultado VARCHAR(20) NOT NULL DEFAULT 'Perdio'
);

ALTER TABLE score
  ADD COLUMN IF NOT EXISTS categoria VARCHAR(40) NOT NULL DEFAULT 'General',
  ADD COLUMN IF NOT EXISTS dificultad VARCHAR(20) NOT NULL DEFAULT 'Media',
  ADD COLUMN IF NOT EXISTS resultado VARCHAR(20) NOT NULL DEFAULT 'Perdio';
