import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useTasks } from '../context/TaskContext'
import { ArrowRight } from 'lucide-react'

export default function CreateTask() {
  // Acciones globales y navegación luego de guardar correctamente.
  const { agregarTarea } = useTasks(), navigate = useNavigate()
  const [form, setForm] = useState({ titulo: '', descripcion: '', fechaTarea: '', completada: false }); const [errors, setErrors] = useState({}); const [message, setMessage] = useState('')
  // Actualiza un campo y limpia únicamente su error cuando el usuario lo corrige.
  const change = (e) => { const { name, value, checked, type } = e.target; setForm((f) => ({ ...f, [name]: type === 'checkbox' ? checked : value })); if (errors[name]) setErrors((err) => ({ ...err, [name]: '' })) }
  // Valida, crea identificador/fecha de creación y guarda la tarea en el contexto.
  const submit = (e) => { e.preventDefault(); const next = {}; if (!form.titulo.trim()) next.titulo = 'El título es obligatorio.'; if (!form.descripcion.trim()) next.descripcion = 'La descripción es obligatoria.'; if (!form.fechaTarea) next.fechaTarea = 'La fecha es obligatoria.'; setErrors(next); if (Object.keys(next).length) return; const id = `${Date.now().toString(36)}-${form.titulo.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').slice(0, 24)}`; agregarTarea({ ...form, titulo: form.titulo.trim(), descripcion: form.descripcion.trim(), id, fechaCreacion: new Date().toISOString().slice(0, 10) }); setMessage('Tarea creada correctamente. Redirigiendo...'); setTimeout(() => navigate(`/tarea/${id}`), 650) }
  return <main className="page narrow-page"><section className="form-heading"><h1>Nueva tarea</h1><p>Creá una tarea para organizar lo que tenés pendiente.</p></section><form className="task-form" onSubmit={submit} noValidate><div className="field"><label htmlFor="titulo">Título <b>*</b></label><input id="titulo" name="titulo" value={form.titulo} onChange={change} className={errors.titulo ? 'input-error' : ''} placeholder="Ej. Terminar el informe mensual" autoFocus />{errors.titulo && <small>{errors.titulo}</small>}</div><div className="field"><label htmlFor="descripcion">Descripción <b>*</b></label><textarea id="descripcion" name="descripcion" value={form.descripcion} onChange={change} className={errors.descripcion ? 'input-error' : ''} placeholder="Agregá detalles que te ayuden a completar esta tarea..." rows="5" />{errors.descripcion && <small>{errors.descripcion}</small>}</div><div className="field"><label htmlFor="fechaTarea">Fecha <b>*</b></label><input id="fechaTarea" type="date" name="fechaTarea" value={form.fechaTarea} onChange={change} className={errors.fechaTarea ? 'input-error' : ''}/>{errors.fechaTarea && <small>{errors.fechaTarea}</small>}</div><label className="switch-row"><input type="checkbox" name="completada" checked={form.completada} onChange={change}/><span className="switch"></span><span><strong>Completada</strong><small>Podés cambiar este estado más adelante.</small></span></label>{message && <p className="success-message" role="status">✓ {message}</p>}<div className="form-actions"><button type="button" className="button button-ghost" onClick={() => navigate(-1)}>Cancelar</button><button className="button" type="submit">Crear tarea <ArrowRight size={16}/></button></div></form></main>
}
